version: "3.1"
services:

############################
#           EMQX           #
#       (Port 18083)       #
############################
  emqx:
    image: emqx/emqx:4.3.2
    container_name: EMQX
    restart: always
    ports:
      - 8083:8083
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8084:8084
      - 8085:8081
    environment:
       EMQX_NAME: mi-emqtt
       EMQX_HOST: 127.0.0.1
       EMQX_ALLOW_ANONYMOUS: "false"
       EMQX_NOMATCH: "deny"
       TZ: "Europe/Madrid"
       EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "# YOUR EMXQ PASSWORD"
       EMQX_DASHBOARD__DEFAULT_USER__LOGIN: "# YOUR EMQX USERNAME"
       EMQX_AUTH__USER__1__USERNAME: "# YOUR USER EMQX USERNAME"
       EMQX_AUTH__USER__1__PASSWORD: "# YOUR USER EMQX PASSWORD"
       EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mnesia"

############################
#           MYSQL          #
#                          #
############################
  db:
    image: hypriot/rpi-mysql
    container_name: my-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: # YOUR MYSQL ROOT PASSWORD
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: # YOUR MYSQL USERNAME
      MYSQL_PASSWORD: # YOUR MYSQL PASSWORD


############################
#          ADMINER         #
#        (Port 5050)       #
############################
  adminer:
    image: adminer
    container_name: my-adminer
    restart: always
    ports:
      - 5050:8080